#GENERAL
APP_NAME = 'MetricMind'
USER_ID = 'default_user'

#MODELS
STARTER_AGENT_MODEL = 'gemini-2.5-flash'
SQL_WRITER_AGENT_MODEL = 'gemini-2.5-flash'
SQL_CRITIC_AGENT_MODEL = 'gemini-2.5-flash'
SQL_REFINER_AGENT_MODEL = 'gemini-2.5-flash'
PYTHON_WRITER_AGENT_MODEL = 'gemini-2.5-flash'
PYTHON_CRITIC_AGENT_MODEL = 'gemini-2.5-flash'
PYTHON_REFINER_AGENT_MODEL = 'gemini-2.5-flash'

#AGENT CALLBACK PHRASE
OUTCOME_OK_PHRASE = "OUTCOME OK"

#DATA SCHEMA
DATA_SCHEMA_PATH = 'data_schema.json'

#MAX_RETRIES
MAX_RETRIES = 3



